version: 1

# path to main.go (adjust if it lives in cmd/review-board)
main: .

# file that will be attached to the GitHub Release
filename: Openhands-LIST-MCP

goos:   linux
goarch: amd64

flags:
  - -trimpath
ldflags:
  - -s -w        # strip symbols → smaller binary
env:
  - CGO_ENABLED=0
