# SLSA-Goreleaser configuration for Openhands-LIST-MCP
# Docs: https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md
version: 0.2

goos:   [linux]
goarch: [amd64]
targets:
  - ./cmd/review-board    # <-- adjust if your main package lives elsewhere

build-flags:
  - -trimpath
  - -ldflags="-s -w"

artifacts:
  - type: binary
    id: review-board
    goos:   linux
    goarch: amd64
    path:   ./cmd/review-board      # same as above
    # output name is inferred (review-board_linux_amd64)

provenance:
  enabled: true
