version: 1                # required

goos:   linux                # ← scalar, not [linux]
goarch: amd64                # ← scalar, not [amd64]

targets:
  - .                        # path of the main package (root).  change if main is in cmd/…
filename: Openhands-LIST-MCP
build-flags:
  - -trimpath
  - -ldflags=-s -w

artifacts:
  - type: binary
    id: review-board         # label in the provenance file
    path: .                  # same path as in targets
    goos:   linux
    goarch: amd64

provenance:
  enabled: true
